main:
  - name: Bio
    url: /ja/
    weight: 10
  - name: Papers
    url: /ja/publications/
    weight: 11
  - name: News
    url: /ja/news/
    weight: 13
  - name: Experience
    url: /ja/experience/
    weight: 20
  - name: Projects
    url: /ja/projects/
    weight: 30
